name: TeamQuests
version: '1.0'
main: me.uyuyuy99.teamquests.TeamQuests
api-version: '1.20'
permissions:
  teamquests.info:
    description: View your team info
    default: true
  teamquests.create:
    description: Create teams
    default: true
  teamquests.invite:
    description: Invite players to your team
    default: true
  teamquests.join:
    description: Join a team (if invited)
    default: true
  teamquests.leave:
    description: Leave your team
    default: true
  teamquests.quests:
    description: View the team quests menu
    default: true